# Generated by Django 5.0 on 2023-12-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_course', models.CharField(max_length=120, verbose_name='Dersin Adini Giriniz')),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_description', models.TextField()),
                ('A', models.CharField(max_length=120, verbose_name='A')),
                ('B', models.CharField(max_length=120, verbose_name='B')),
                ('C', models.CharField(max_length=120, verbose_name='C')),
                ('D', models.CharField(max_length=120, verbose_name='D')),
                ('E', models.CharField(max_length=120, verbose_name='E')),
            ],
        ),
    ]
