# Generated by Django 5.0 on 2023-12-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_question_true_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='True_choice',
            field=models.CharField(choices=[(models.CharField(max_length=120, verbose_name='A'), 'A'), (models.CharField(max_length=120, verbose_name='B'), 'B'), (models.CharField(max_length=120, verbose_name='C'), 'C'), (models.CharField(max_length=120, verbose_name='D'), 'D'), (models.CharField(max_length=120, verbose_name='E'), 'E')], max_length=3, verbose_name='true_choice'),
        ),
    ]
