# Generated by Django 5.0 on 2023-12-18 12:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_question_image_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
