# Generated by Django 5.0 on 2023-12-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_question_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='question_course',
            new_name='course_name',
        ),
        migrations.AddField(
            model_name='courses',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='question_asked',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='question_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
