# Generated by Django 5.0 on 2023-12-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_question_number_courses_total_question_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('student_email', models.CharField(max_length=30)),
                ('soru_1', models.PositiveIntegerField()),
                ('soru_2', models.PositiveIntegerField()),
                ('soru_3', models.PositiveIntegerField()),
                ('soru_4', models.PositiveIntegerField()),
                ('soru_5', models.PositiveIntegerField()),
            ],
        ),
    ]
