# Generated by Django 5.0 on 2023-12-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_student_data_student_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_data',
            name='soru_4',
        ),
        migrations.RemoveField(
            model_name='student_data',
            name='soru_5',
        ),
    ]
