# Generated by Django 5.0 on 2023-12-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_student_data_soru_4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_data',
            old_name='course_name',
            new_name='courseid',
        ),
        migrations.RenameField(
            model_name='student_data',
            old_name='user_id',
            new_name='userid',
        ),
    ]
