# Generated by Django 5.0 on 2023-12-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_rename_course_name_student_data_courseid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='total_question_number',
            field=models.PositiveIntegerField(),
        ),
    ]
