# Generated by Django 5.0 on 2023-12-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_courses_total_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='total_question_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
