# Generated by Django 5.0 on 2023-12-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_courses_total_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='soru_1',
            field=models.PositiveIntegerField(default='not_asked'),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='soru_2',
            field=models.PositiveIntegerField(default='not_asked'),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='soru_3',
            field=models.PositiveIntegerField(default='not_asked'),
        ),
    ]
