# Generated by Django 5.0 on 2023-12-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_student_data_soru_1_alter_student_data_soru_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='soru_1',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='soru_2',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='soru_3',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
