# Generated by Django 5.0 on 2023-12-20 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_student_data_courseid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='courseid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.courses'),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
