# Generated by Django 5.0 on 2023-12-20 19:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_student_data_courseid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student_data',
            new_name='student_answer_data',
        ),
    ]
