# Generated by Django 5.0 on 2023-12-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_rename_student_data_student_answer_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_time_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru1_time', models.PositiveIntegerField(default=0)),
                ('soru2_time', models.PositiveIntegerField(default=0)),
                ('soru3_time', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
