# Generated by Django 5.0 on 2023-12-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_student_time_data_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_answer_data',
            name='numberoftest',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
