# Generated by Django 5.0 on 2023-12-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_student_answer_data_numberoftest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_answer_data',
            name='numberoftest',
            field=models.PositiveIntegerField(),
        ),
    ]
