# Generated by Django 5.0 on 2023-12-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_alter_student_answer_data_numberoftest'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_time_data',
            name='numberoftest_time',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student_answer_data',
            name='numberoftest',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
