# Generated by Django 5.0 on 2023-12-21 18:01

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_student_time_data_numberoftest_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='blogs', validators=[blog.models.validate_unique_image_name]),
        ),
    ]
