# Generated by Django 5.0 on 2023-12-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_alter_question_a_alter_question_b_alter_question_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
