# Generated by Django 5.0 on 2023-12-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_alter_question_question_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(upload_to='blogs'),
        ),
    ]
