# Generated by Django 5.0 on 2023-12-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_alter_courses_total_question_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_answer_data',
            name='soru_1',
        ),
        migrations.RemoveField(
            model_name='student_answer_data',
            name='soru_2',
        ),
        migrations.RemoveField(
            model_name='student_answer_data',
            name='soru_3',
        ),
    ]
