# Generated by Django 5.0 on 2023-12-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_student_answer_data_soru_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_answer_data',
            name='soru_1',
        ),
        migrations.RemoveField(
            model_name='student_answer_data',
            name='soru_2',
        ),
        migrations.RemoveField(
            model_name='student_answer_data',
            name='soru_3',
        ),
    ]
