# Generated by Django 5.0 on 2023-12-22 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_answer_data',
            name='courseid',
        ),
        migrations.RemoveField(
            model_name='student_answer_data',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='student_time_data',
            name='student_id',
        ),
        migrations.CreateModel(
            name='student_all_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theanswer', models.PositiveIntegerField(default=2)),
                ('theanswertime', models.PositiveIntegerField(default=0)),
                ('istested', models.BooleanField(default=False)),
                ('numberoftest', models.PositiveIntegerField(default=1)),
                ('courseid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.courses')),
                ('questionid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.question')),
                ('userid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='student_answer_data',
        ),
        migrations.DeleteModel(
            name='student_time_data',
        ),
    ]
