# Generated by Django 5.0 on 2023-12-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_number_of_tests_taken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='number_of_tests_taken',
            old_name='course',
            new_name='course_tested',
        ),
        migrations.RenameField(
            model_name='number_of_tests_taken',
            old_name='user',
            new_name='user_tested',
        ),
    ]
