# Generated by Django 5.0 on 2023-12-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_rename_course_tested_number_of_tests_taken_courseid_tested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_all_data',
            name='numberoftest',
        ),
    ]
