# Generated by Django 5.0 on 2023-12-23 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_remove_student_all_data_numberoftest'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_all_data',
            name='tests_taken_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.number_of_tests_taken'),
        ),
    ]
