# Generated by Django 5.0 on 2023-12-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_student_all_data_tests_taken_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_all_data',
            name='answertime',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
