# Generated by Django 5.0 on 2023-12-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_student_all_data_answertime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_all_data',
            name='answertime',
        ),
    ]
