# Generated by Django 5.0 on 2023-12-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_remove_student_all_data_answertime'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_all_data',
            name='extragrade',
            field=models.IntegerField(default=0),
        ),
    ]
