# Generated by Django 5.0 on 2023-12-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0055_student_all_data_extragrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='devolement_mode',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
