# Generated by Django 5.0 on 2023-12-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0056_courses_devolement_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='devolement_mode',
            field=models.BooleanField(),
        ),
    ]
