# Generated by Django 5.0 on 2023-12-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0058_rename_is_active_courses_course_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='number_of_tests_taken',
            name='development_mode_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
