# Generated by Django 5.0 on 2023-12-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0060_alter_number_of_tests_taken_development_mode_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='devolement_mode',
            new_name='development_mode',
        ),
    ]
