# Generated by Django 5.0 on 2024-01-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0063_acceptanceofrules'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptanceofrules',
            name='user_rule_acceptance',
            field=models.BooleanField(default=False),
        ),
    ]
