# Generated by Django 5.0 on 2024-01-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0064_acceptanceofrules_user_rule_acceptance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptanceofrules',
            old_name='user_rule_acceptance',
            new_name='user_rules_acceptance',
        ),
    ]
