# Generated by Django 5.0 on 2024-01-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0065_rename_user_rule_acceptance_acceptanceofrules_user_rules_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='student_solve_exam_once',
            field=models.BooleanField(default=False),
        ),
    ]
